language: cpp
compiler:
  - gcc
  - clang
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default
script:
  - qmake -v
  - qmake
  - make
  - export LD_LIBRARY_PATH=lib/:$LD_LIBRARY_PATH
  - tests/qosdnotificationmanager_tst/tst_qosdnotificationmanager
  - tests/qosdnotification_tst/tst_qosdnotification
