language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default
script:
  - qmake -v
  - qmake
  - make
