#ifndef QOSDNOTIFICATION_GLOBAL_H
#define QOSDNOTIFICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QOSDNOTIFICATION_LIBRARY)
#  define QOSDNOTIFICATION_EXPORT Q_DECL_EXPORT
#else
#  define QOSDNOTIFICATION_EXPORT Q_DECL_IMPORT
#endif

#endif // QOSDNOTIFICATION_GLOBAL_H
